/*
    This file is part of Calculadora-CdE

    Calculadora-CdE is free software: you can redistribute it and/or modify
    it under the terms of the Affero GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    Calculadora-CdE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    Affero GNU General Public License for more details.

    You should have received a copy of the Affero GNU General Public License
    along with Calculadora-CdE.  If not, see <http://www.gnu.org/licenses/>.
   
    1.0 23 April 2012
    1.1 29 Juny  2012

    © Copyright 2012
    Eduard Gamonal <eduard.gamonal at est.fib.upc dot edu>
    Jordi Nonell <jordi.nopa at gmail dot com>
*/

/*
 * Inclou carreres dels plans antics i graus.
 * El preu per grau està extret de http://premsa.gencat.cat/pres_fsvp/AppJava/notapremsavw/detall.do?id=154160&idioma=0
 * Dossier http://premsa.gencat.cat/pres_fsvp/docs/2012/06/29/14/15/b08792ab-3392-4dcf-86d9-43b616f8af83.pdf
 * S'agafa el llindar2 com referència.
 */

var carreres = [
{label:"[Grau] Administració i direcció d’empreses",preu:"15.16"},
{label:"[Grau] Anglès",preu:"15.16"},
{label:"[Grau] Antropologia social i cultural",preu:"15.16"},
{label:"[Grau] Ciència política i gestió pública",preu:"15.16"},
{label:"[Grau] Ciències empresarials",preu:"15.16"},
{label:"[Grau] Ciències polítiques i de l’Administració",preu:"15.16"},
{label:"[Grau] Comptabilitat i finances",preu:"15.16"},
{label:"[Grau] Comunicació cultural",preu:"15.16"},
{label:"[Grau] Criminologia",preu:"15.16"},
{label:"[Grau] Criminologia i polítiques públiques de prevenció",preu:"15.16"},
{label:"[Grau] Dret",preu:"15.16"},
{label:"[Grau] Economia",preu:"15.16"},
{label:"[Grau] Educació infantil",preu:"15.16"},
{label:"[Grau] Educació primària",preu:"15.16"},
{label:"[Grau] Educació social",preu:"15.16"},
{label:"[Grau] Empresa i tecnologia",preu:"15.16"},
{label:"[Grau] Estudis anglesos",preu:"15.16"},
{label:"[Grau] Estudis àrabs i hebreus",preu:"15.16"},
{label:"[Grau] Estudis catalans i occitans",preu:"15.16"},
{label:"[Grau] Estudis clàssics",preu:"15.16"},
{label:"[Grau] Estudis d’anglès i català",preu:"15.16"},
{label:"[Grau] Estudis d’anglès i de clàssiques",preu:"15.16"},
{label:"[Grau] Estudis d’anglès i espanyol",preu:"15.16"},
{label:"[Grau] Estudis d’anglès i francès",preu:"15.16"},
{label:"[Grau] Estudis de català i de clàssiques",preu:"15.16"},
{label:"[Grau] Estudis de català i espanyol",preu:"15.16"},
{label:"[Grau] Estudis de francès i català",preu:"15.16"},
{label:"[Grau] Estudis de francès i de clàssiques",preu:"15.16"},
{label:"[Grau] Estudis de francès i espanyol",preu:"15.16"},
{label:"[Grau] Estudis d’espanyol i de clàssiques",preu:"15.16"},
{label:"[Grau] Estudis francesos",preu:"15.16"},
{label:"[Grau] Estudis hispànics: llengua i literatura",preu:"15.16"},
{label:"[Grau] Estudis internacionals d’economia i empresa/International Business Economics",preu:"15.16"},
{label:"[Grau] Estudis literaris",preu:"15.16"},
{label:"[Grau] Filologia catalana",preu:"15.16"},
{label:"[Grau] Filologia clàssica",preu:"15.16"},
{label:"[Grau] Filologia hispànica",preu:"15.16"},
{label:"[Grau] Filologia romànica",preu:"15.16"},
{label:"[Grau] Filosofia",preu:"15.16"},
{label:"[Grau] Finances i comptabilitat",preu:"15.16"},
{label:"[Grau] Geografia",preu:"15.16"},
{label:"[Grau] Geografia i ordenació del territori",preu:"15.16"},
{label:"[Grau] Geografia i ordenació del territori -en xarxa-",preu:"15.16"},
{label:"[Grau] Geografia,preu: ordenació del territori i gestió del medi ambient"},
{label:"[Grau] Gestió d’empreses",preu:"15.16"},
{label:"[Grau] Gestió i administració pública",preu:"15.16"},
{label:"[Grau] Història",preu:"15.16"},
{label:"[Grau] Història de l’art",preu:"15.16"},
{label:"[Grau] Humanitats",preu:"15.16"},
{label:"[Grau] Lingüística",preu:"15.16"},
{label:"[Grau] Llengua i literatura catalanes",preu:"15.16"},
{label:"[Grau] Llengua i literatura espanyoles",preu:"15.16"},
{label:"[Grau] Llengua i literatura hispàniques",preu:"15.16"},
{label:"[Grau] Llengües i literatures modernes",preu:"15.16"},
{label:"[Grau] Mestre d’educació infantil",preu:"15.16"},
{label:"[Grau] Mestre d’educació primària",preu:"15.16"},
{label:"[Grau] Musicologia",preu:"15.16"},
{label:"[Grau] Pedagogia",preu:"15.16"},
{label:"[Grau] Relacions laborals",preu:"15.16"},
{label:"[Grau] Relacions laborals i ocupació",preu:"15.16"},
{label:"[Grau] Sociologia",preu:"15.16"},
{label:"[Grau] Treball social",preu:"15.16"},
{label:"[Grau] Turisme",preu:"15.16"},
{label:"[Grau] Arqueologia",preu:"21.46"},
{label:"[Grau] Arquitectura",preu:"21.46"},
{label:"[Grau] Belles arts",preu:"21.46"},
{label:"[Grau] Biologia",preu:"21.46"},
{label:"[Grau] Biologia ambiental",preu:"21.46"},
{label:"[Grau] Bioquímica",preu:"21.46"},
{label:"[Grau] Bioquímica i biologia molecular",preu:"21.46"},
{label:"[Grau] Biotecnologia",preu:"21.46"},
{label:"[Grau] Ciència i salut animal",preu:"21.46"},
{label:"[Grau] Ciència i tecnologia dels aliments",preu:"21.46"},
{label:"[Grau] Ciències ambientals",preu:"21.46"},
{label:"[Grau] Ciències i tecnologies de telecomunicació",preu:"21.46"},
{label:"[Grau] Comunicació audiovisual",preu:"21.46"},
{label:"[Grau] Comunicació i industries culturals",preu:"21.46"},
{label:"[Grau] Comunicació i periodisme audiovisuals",preu:"21.46"},
{label:"[Grau] Conservació-restauració de béns culturals",preu:"21.46"},
{label:"[Grau] Disseny",preu:"21.46"},
{label:"[Grau] Enginyeria agrària i alimentària",preu:"21.46"},
{label:"[Grau] Enginyeria agrícola",preu:"21.46"},
{label:"[Grau] Enginyeria agroalimentària",preu:"21.46"},
{label:"[Grau] Enginyeria agroambiental i del paisatge",preu:"21.46"},
{label:"[Grau] Enginyeria alimentària",preu:"21.46"},
{label:"[Grau] Enginyeria civil",preu:"21.46"},
{label:"[Grau] Enginyeria d’aeronavegació",preu:"21.46"},
{label:"[Grau] Enginyeria d’aeroports",preu:"21.46"},
{label:"[Grau] Enginyeria de disseny industrial i desenvolupament del producte",preu:"21.46"},
{label:"[Grau] Enginyeria de la construcció",preu:"21.46"},
{label:"[Grau] Enginyeria de materials",preu:"21.46"},
{label:"[Grau] Enginyeria de recursos minerals",preu:"21.46"},
{label:"[Grau] Enginyeria de sistemes audiovisuals",preu:"21.46"},
{label:"[Grau] Enginyeria de sistemes biològics",preu:"21.46"},
{label:"[Grau] Enginyeria de sistemes de telecomunicació",preu:"21.46"},
{label:"[Grau] Enginyeria de sistemes electrònics",preu:"21.46"},
{label:"[Grau] Enginyeria de sistemes TIC",preu:"21.46"},
{label:"[Grau] Enginyeria de tecnologia i disseny tèxtil",preu:"21.46"},
{label:"[Grau] Enginyeria d’edificació",preu:"21.46"},
{label:"[Grau] Enginyeria elèctrica",preu:"21.46"},
{label:"[Grau] Enginyeria electrònica de telecomunicació",preu:"21.46"},
{label:"[Grau] Enginyeria electrònica industrial i automàtica",preu:"21.46"},
{label:"[Grau] Enginyeria en sistemes audiovisuals",preu:"21.46"},
{label:"[Grau] Enginyeria en sistemes i tecnologia naval",preu:"21.46"},
{label:"[Grau] Enginyeria en tecnologies aeroespacials",preu:"21.46"},
{label:"[Grau] Enginyeria en tecnologies industrials",preu:"21.46"},
{label:"[Grau] Enginyeria en vehicles aeroespacials",preu:"21.46"},
{label:"[Grau] Enginyeria física",preu:"21.46"},
{label:"[Grau] Enginyeria forestal",preu:"21.46"},
{label:"[Grau] Enginyeria geològica",preu:"21.46"},
{label:"[Grau] Enginyeria geomàtica i topografia",preu:"21.46"},
{label:"[Grau] Enginyeria informàtica",preu:"21.46"},
{label:"[Grau] Enginyeria marina",preu:"21.46"},
{label:"[Grau] Enginyeria mecànica",preu:"21.46"},
{label:"[Grau] Enginyeria nàutica i transport marítim",preu:"21.46"},
{label:"[Grau] Enginyeria química",preu:"21.46"},
{label:"[Grau] Enginyeria telemàtica",preu:"21.46"},
{label:"[Grau] Enologia",preu:"21.46"},
{label:"[Grau] Estadística",preu:"21.46"},
{label:"[Grau] Estadística aplicada",preu:"21.46"},
{label:"[Grau] Estudis d’Àsia oriental (japonès)",preu:"21.46"},
{label:"[Grau] Estudis d’Àsia oriental (xinès)",preu:"21.46"},
{label:"[Grau] Farmàcia",preu:"21.46"},
{label:"[Grau] Física",preu:"21.46"},
{label:"[Grau] Genètica",preu:"21.46"},
{label:"[Grau] Geologia",preu:"21.46"},
{label:"[Grau] Gestió aeronàutica",preu:"21.46"},
{label:"[Grau] Informació i documentació",preu:"21.46"},
{label:"[Grau] Llengües aplicades",preu:"21.46"},
{label:"[Grau] Logopèdia",preu:"21.46"},
{label:"[Grau] Matemàtiques",preu:"21.46"},
{label:"[Grau] Microbiologia",preu:"21.46"},
{label:"[Grau] Nanociència i nanotecnologia",preu:"21.46"},
{label:"[Grau] Nutrició humana i dietètica",preu:"21.46"},
{label:"[Grau] Periodisme",preu:"21.46"},
{label:"[Grau] Podologia",preu:"21.46"},
{label:"[Grau] Psicologia",preu:"21.46"},
{label:"[Grau] Publicitat i relacions públiques",preu:"21.46"},
{label:"[Grau] Química",preu:"21.46"},
{label:"[Grau] Traducció i interpretació - alemany",preu:"21.46"},
{label:"[Grau] Traducció i interpretació - anglès",preu:"21.46"},
{label:"[Grau] Traducció i interpretació - francès",preu:"21.46"},
{label:"[Grau] Traducció i interpretació - llengua de signes catalana ",preu:"21.46"},
{label:"[Grau] Biologia humana",preu:"23.72"},
{label:"[Grau] Ciències biomèdiques",preu:"23.72"},
{label:"[Grau] Ciències mèdiques bàsiques",preu:"23.72"},
{label:"[Grau] Enginyeria biomèdica",preu:"23.72"},
{label:"[Grau] Fisioteràpia",preu:"23.72"},
{label:"[Grau] Infermeria",preu:"23.72"},
{label:"[Grau] Medicina",preu:"23.72"},
{label:"[Grau] Odontologia",preu:"23.72"},
{label:"[Grau] Òptica i optometria",preu:"23.72"},
{label:"[Grau] Veterinària",preu:"23.72"},
{label:"Antropologia social i cultural",preu:"11.8"},
{label:"Ciències del treball",preu:"11.8"},
{label:"Ciències polítiques i de l’administració",preu:"11.8"},
{label:"Dret",preu:"11.8"},
{label:"Filologia alemanya",preu:"11.8"},
{label:"Filologia anglesa",preu:"11.8"},
{label:"Filologia àrab",preu:"11.8"},
{label:"Filologia catalana",preu:"11.8"},
{label:"Filologia clàssica",preu:"11.8"},
{label:"Filologia eslava",preu:"11.8"},
{label:"Filologia francesa",preu:"11.8"},
{label:"Filologia gallega",preu:"11.8"},
{label:"Filologia hebrea",preu:"11.8"},
{label:"Filologia hispànica",preu:"11.8"},
{label:"Filologia italiana",preu:"11.8"},
{label:"Filologia portuguesa",preu:"11.8"},
{label:"Filologia romànica",preu:"11.8"},
{label:"Filosofia",preu:"11.8"},
{label:"Història",preu:"11.8"},
{label:"Història de l’art",preu:"11.8"},
{label:"Història i ciències de la música",preu:"11.8"},
{label:"Humanitats",preu:"11.8"},
{label:"Lingüística",preu:"11.8"},
{label:"Sociologia",preu:"11.8"},
{label:"Teoria de la literatura",preu:"11.8"},
{label:"Literatura comparada",preu:"11.8"},
{label:"Gestió i administració pública",preu:"11.8"},
{label:"Relacions laborals",preu:"11.8"},
{label:"Treball social",preu:"11.8"},
{label:"Administració i direcció d’empreses",preu:"12.13"},
{label:"Ciències actuarials i financeres",preu:"12.13"},
{label:"Criminologia",preu:"12.13"},
{label:"Documentació",preu:"12.13"},
{label:"Economia",preu:"12.13"},
{label:"Geografia",preu:"12.13"},
{label:"Investigació i tècniques de mercat",preu:"12.13"},
{label:"Pedagogia",preu:"12.13"},
{label:"Periodisme",preu:"12.13"},
{label:"Psicologia",preu:"12.13"},
{label:"Psicopedagogia",preu:"12.13"},
{label:"Publicitat i relacions públiques",preu:"12.13"},
{label:"Traducció i interpretació (alemany)",preu:"12.13"},
{label:"Traducció i interpretació (anglès",preu:"12.13"},
{label:"Traducció i interpretació (francès)",preu:"12.13"},
{label:"Biblioteconomia i documentació",preu:"12.13"},
{label:"Ciències empresarials",preu:"12.13"},
{label:"Educació social",preu:"12.13"},
{label:"Mestre especialitat en educació especial",preu:"12.13"},
{label:"Mestre Educació física",preu:"12.13"},
{label:"Mestre Educació infantil",preu:"12.13"},
{label:"Mestre Educació musical",preu:"12.13"},
{label:"Mestre Educació primària",preu:"12.13"},
{label:"Mestre Educació en llengua estrangera",preu:"12.13"},
{label:"Belles arts",preu:"16.71"},
{label:"Ciències ambientals",preu:"16.71"},
{label:"Ciències de l’activitat física i de l’esport",preu:"16.71"},
{label:"Ciències i tècniques estadístiques",preu:"16.71"},
{label:"Comunicació audiovisual",preu:"16.71"},
{label:"Estudis d’Àsia Oriental",preu:"16.71"},
{label:"Física",preu:"16.71"},
{label:"Matemàtiques",preu:"16.71"},
{label:"Estadística",preu:"16.71"},
{label:"Màquines navals",preu:"16.71"},
{label:"Navegació marítima",preu:"16.71"},
{label:"Turisme",preu:"16.71"},
{label:"Enginyeria en informàtica",preu:"16.71"},
{label:"Enginyeria en organització industrial",preu:"16.71"},
{label:"Arquitectura",preu:"16.71"},
{label:"Enginyeria tècnica aeronàutica",preu:"16.71"},
{label:"Especialitat en aeronavegació",preu:"16.71"},
{label:"Enginyeria tècnica agrícola",preu:"16.71"},
{label:"Enginyeria tècnica agrícola (Explotacions agropecuàries)",preu:"16.71"},
{label:"Enginyeria tècnica agrícola (Hortofructicultura i jardineria)",preu:"16.71"},
{label:"Enginyeria tècnica agrícola (Indústries agràries i alimentàries)",preu:"16.71"},
{label:"Enginyeria tècnica agrícola (Mecanització i construccions rurals)",preu:"16.71"},
{label:"Enginyeria tècnica forestal (Explotacions forestals)",preu:"16.71"},
{label:"Enginyeria tècnica forestal (Indústries forestals)",preu:"16.71"},
{label:"Enginyeria tècnica industrial (Electricitat)",preu:"16.71"},
{label:"Enginyeria tècnica industrial (Electrònica industrial)",preu:"16.71"},
{label:"Enginyeria tècnica industrial (Mecànica)",preu:"16.71"},
{label:"Enginyeria tècnica industrial (Química industrial)",preu:"16.71"},
{label:"Enginyeria tècnica industrial (Tèxtil)",preu:"16.71"},
{label:"Enginyeria tècnica en informàtica de gestió",preu:"16.71"},
{label:"Enginyeria tècnica en informàtica de sistemes",preu:"16.71"},
{label:"Enginyeria tècnica de mines (Explotació de mines)",preu:"16.71"},
{label:"Enginyeria tècnica d’obres públiques (Especialitat en construccions civils)",preu:"16.71"},
{label:"Enginyeria tècnica d’obres públiques (Hidrologia)",preu:"16.71"},
{label:"Enginyeria tècnica d’obres públiques (Transports)",preu:"16.71"},
{label:"Enginyeria tècnica d’obres públiques (Serveis urbans)",preu:"16.71"},
{label:"Enginyeria tècnica en disseny industrial",preu:"16.71"},
{label:"Enginyeria tècnica de telecomunicació (so i imatge)",preu:"16.71"},
{label:"Enginyeria tècnica en topografia",preu:"16.71"},
{label:"Enginyeria tècnica de telecomunicació",preu:"16.71"},
{label:"Enginyeria tècnica de telecomunicació (sistemes electrònics)",preu:"16.71"},
{label:"Enginyeria tècnica de telecomunicació (sistemes de telecomunicació)",preu:"16.71"},
{label:"Enginyeria tècnica de telecomunicació (telemàtica)",preu:"16.71"},
{label:"Enginyeria tècnica naval (Propulsió)",preu:"16.71"},
{label:"Enginyeria tècnica naval (Serveis del vaixell)",preu:"16.71"},
{label:"Arquitectura tècnica",preu:"16.71"},
{label:"Biologia",preu:"17.15"},
{label:"Biotecnologia",preu:"17.15"},
{label:"Bioquímica",preu:"17.15"},
{label:"Ciència i tecnologia dels aliments",preu:"17.15"},
{label:"Enologia",preu:"17.15"},
{label:"Farmàcia",preu:"17.15"},
{label:"Geologia",preu:"17.15"},
{label:"Màquines navals",preu:"17.15"},
{label:"Medicina",preu:"17.15"},
{label:"Nàutica i transport marítim",preu:"17.15"},
{label:"Odontologia",preu:"17.15"},
{label:"Química",preu:"17.15"},
{label:"Veterinària",preu:"17.15"},
{label:"Enginyeria agronòmica",preu:"17.15"},
{label:"Enginyeria aeronàutica",preu:"17.15"},
{label:"Enginyeria en automàtica i electrònica industrial",preu:"17.15"},
{label:"Enginyeria de camins canals i ports",preu:"17.15"},
{label:"Enginyeria en electrònica",preu:"17.15"},
{label:"Enginyeria de forests",preu:"17.15"},
{label:"Enginyer geòleg",preu:"17.15"},
{label:"Enginyeria industrial",preu:"17.15"},
{label:"Enginyeria química",preu:"17.15"},
{label:"Enginyeria de materials",preu:"17.15"},
{label:"Enginyeria de telecomunicació",preu:"17.15"},
{label:"Enginyeria de mines",preu:"17.15"},
{label:"Fisioteràpia",preu:"17.15"},
{label:"Infermeria",preu:"17.15"},
{label:"Logopèdia",preu:"17.15"},
{label:"Nutrició humana i dietètica",preu:"17.15"},
{label:"Òptica i optometria",preu:"17.15"},
{label:"Podologia",preu:"17.15"},
{label:"Teràpia ocupacional",preu:"17.15"}
];


/*
 * taula que enregistra els ingressos màxims  (llindars) segons
 * el num de membres de la unitat familiar.
 * format:
 * 
 */
var iml = 
[
    [14112, 14112, 15000, 15889, 16777, 20331], /* 1 membre */
    [24089, 24089, 25745, 27400, 29056, 35678], /* 2 membres */
    [32697, 32697, 33788, 34878, 35969, 40331], /* 3 membres */
    [38831, 38831, 39733, 40635, 41536, 45144], /* 4 membres */
    [43403, 43403, 44304, 45206, 46107, 49715], /* 5 membres */
    [46853, 46853, 47755, 48657, 49558, 53166], /* 6 membres */
    [50267, 50267, 51169, 52071, 52972, 56580], /* 7 membres */
    [53665, 53665, 54567, 55469, 56370, 59978], /* 8 membres */    
];
